//
// Generated by JSON Model Compiler version 2.0b36
// see https://github.com/clairey-zx81/json-model
//
package main

import (
    "fmt"
    "regexp"
    jm "jsonmodel/json_model/runtime/go/jsonmodel"
)

type Checker func(interface{}, *jm.Path, *jm.Report) bool


    var _jm_re_0_re *regexp.Regexp
    var check_model_map map[string]Checker

    func _jm_re_0(val string, path *jm.Path, rep *jm.Report) bool {
        return _jm_re_0_re.MatchString(val)
    }

    // check $ (.)
    func json_model_1(val interface{}, path *jm.Path, rep *jm.Report) bool {
        // A person with a birth date
        // .
        // check close must only props
        if ! jm.IsObject(val) {
            if rep != nil { rep.Add("not an object [.]", path) }
            return false
        }
        if jm.Len(val) != 2 {
            if rep != nil { rep.Add("bad property count [.]", path) }
            return false
        }
        var lpath *jm.Path
        var pval interface{}
        var res bool
        if ! jm.ObjectHasPropVal(val, "name", &pval) {
            if rep != nil { rep.Add("missing mandatory prop <name> [.]", path) }
            return false
        }
        lpath = jm.ExtendPath(path, "name")
        // .name
        // "/^[a-z]+$/i"
        res = jm.IsString(pval) && _jm_re_0(jm.AsString(pval), jm.SelectPath(lpath, path != nil), rep)
        if ! res {
            if rep != nil { rep.Add("unexpected /^[a-z]+$/i [.name]", jm.SelectPath(lpath, path != nil)) }
            if rep != nil { rep.Add("unexpected value for mandatory prop <name> [.]", jm.SelectPath(lpath, path != nil)) }
            return false
        }
        if ! jm.ObjectHasPropVal(val, "born", &pval) {
            if rep != nil { rep.Add("missing mandatory prop <born> [.]", path) }
            return false
        }
        lpath = jm.ExtendPath(path, "born")
        // .born
        res = jm.IsString(pval) && jm.IsValidDate(jm.AsString(pval))
        if ! res {
            if rep != nil { rep.Add("unexpected $DATE [.born]", jm.SelectPath(lpath, path != nil)) }
            if rep != nil { rep.Add("unexpected value for mandatory prop <born> [.]", jm.SelectPath(lpath, path != nil)) }
            return false
        }
        return true
    }


    var initialized bool

    func check_model_init() {
    	if !initialized {
    		defer func() {
    			if r := recover(); r != nil {
    				panic(fmt.Sprintf("cannot initialize model checker: %v", r))
    			}
    		}()

            _jm_re_0_re = regexp.MustCompile("(?i)^[a-z]+$")
            check_model_map = map[string]Checker{
                "": json_model_1,
            }
    		initialized = true
    	}
    }

    func check_model_free() {
    	if initialized {
    		initialized = false
    	}
    }
